server:
  port: 8302
zuul:
  sensitiveHeaders: Cookie
  routes:
    order-service:
      path: /order-service/**
      url: http://localhost:8081
    order-item-service:
      path: /order-item-service/**
      url: http://localhost:8082

spring.application.name: gateway
zuul.host.connect-timeout-millis: 500000
zuul.host.socket-timeout-millis: 500000
zuul.sensitiveHeaders:
spring.servlet.multipart.max-file-size: 30MB
spring.servlet.multipart.max-request-size: 30MB
logging.pattern.console: "%d %-5level %logger : %msg%n"
logging.level.org.springframework.web: ERROR
logging.level.com.dbs: info
logging.level.org.hibernate: ERROR
eureka.client.service-url.defaultZone: http://localhost:8761
