server.port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:order-item
    driverClassName: org.h2.Driver
    username: sa
    password:
#    url: jdbc:mariadb://localhost:3306/gene_local
#    username: root
#    password:
  data.jpa:
    repositories:
      bootstrap-mode=default:
  jpa:
    show-sql: false
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: update

  application.name: order-item-service

eureka.client:
   service-url:
      defaultZone: http://localhost:8761/eureka





spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB

logging.pattern.console: "%d %-5level [%t] %logger : %msg%n"
logging.level.org.springframework.web: ERROR
logging.level.com.dbs: info
#logging.level.org.hibernate: INFO











